### PR TITLE
[feature] increase to angular 17

### PR DESCRIPTION
**Pull request by phhbr**
Fixes https://github.com/shipshapecode/angular-shepherd/issues/2110

### CODE REVIEW

**Review by rajpeddalachugari — APPROVED** [review]

**Review by VikashRepo123 — APPROVED** [review]
Approved

**Comment by RobbieTheWagner** [comment]
@phhbr it looks like node version needs to be updated. CI will not run.

**Comment by RobbieTheWagner** [comment]
@phhbr looks like we have this error now `Error: Module not found: Error: Package path ./dist/zone-testing `

**Comment by rajpeddalachugari** [comment]
@phhbr could you please generate the build as soon as possible . our upgrade process is dependent on this 😄

**Pull request merged**
