### PR TITLE
update to angular 16

### PR DESCRIPTION
**Pull request by tomer953**
a new PR with latest angular 16.1.4

### CODE REVIEW

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
@tomer953 looks like tests are failing because we need to update node

**Comment by tomer953** [comment]
> @tomer953 looks like tests are failing because we need to update node

yes i see, sorry about that. 
do you want me to create a fix? ill do tomorrow

**Comment by tomer953** [comment]
try now ?

**Comment by tomer953** [comment]
thank you. 
plz don't forget ro publish to npm

**Pull request merged**
