### PR TITLE
Update to Angular 16

### PR DESCRIPTION
**Pull request by tomer953**

### CODE REVIEW

**Comment by dschweinbenz** [comment]
push

**Comment by blockerdude** [comment]
I'm also hoping this can be resolved soon!

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by RobbieTheWagner** [comment]
Apologies for the delay. I wish Angular would make this easier, since nothing has actually changed in our code. We should be able to support a range of Angular versions, but alas, we cannot. I have approved now. Could you please rebase to fix the conflicts?

**Comment by tomer953** [comment]
a new PR - https://github.com/shipshapecode/angular-shepherd/pull/1932

**Pull request closed without merging**
